env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - react-hooks
rules:
  quotes:
    - 2
    - double
  brace-style:
    - 2
    - stroustrup
  import/no-unresolved:
    - 1
    - caseSensitive: false
